# Snowy starship prompt
add_newline = false
continuation_prompt = "[▸▹ ](dimmed bright-cyan)"

format = """$username$hostname$directory$git_branch$git_status$cmd_duration\n$character"""

[character]
success_symbol = "[❄](bold bright-cyan)"
error_symbol = "[○](bold bright-blue)"
vimcmd_symbol = "[■](italic dimmed bright-cyan)"

[username]
style_user = "bright-cyan bold"
style_root = "bright-blue bold"
format = "[$user]($style) "
show_always = false

[hostname]
ssh_only = false
style = "bright-cyan bold"
format = "[@$hostname]($style) "

[directory]
style = "italic bright-cyan"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "⌂"
read_only = " "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bright-cyan bold"
format = "[$symbol$branch]($style) "

[git_status]
style = "bright-blue bold"
format = "([$all_status$ahead_behind]($style))"

[cmd_duration]
min_time = 200
format = "[◀ $duration ](italic bright-white)"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%H:%M"
style = "italic dimmed bright-white"

[jobs]
format = "[$symbol$number]($style) "
style = "bright-cyan"
symbol = "[▶](bright-cyan italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold bright-cyan)"
disabled = false

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-cyan"
symbol = "≈ˆ"
disabled = false

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold bright-cyan)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold bright-blue"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-blue"

[[battery.display]]
threshold = 80
style = "italic dimmed bright-cyan"
