$primary_paletteKeyColor = a8d9ff
$secondary_paletteKeyColor = c6d7ea
$tertiary_paletteKeyColor = b7f2ff
$neutral_paletteKeyColor = 7f8fa3
$neutral_variant_paletteKeyColor = 6f8398
$background = 0b1118
$onBackground = eaf4ff
$surface = 0f1721
$surfaceDim = 0b1118
$surfaceBright = 1b2736
$surfaceContainerLowest = 091018
$surfaceContainerLow = 111b28
$surfaceContainer = 15202f
$surfaceContainerHigh = 1a2838
$surfaceContainerHighest = 223345
$onSurface = eaf4ff
$surfaceVariant = 31465a
$onSurfaceVariant = c6d3e2
$inverseSurface = eaf4ff
$inverseOnSurface = 121b26
$outline = 7d90a8
$outlineVariant = 31465a
$shadow = 000000
$scrim = 000000
$surfaceTint = a8d9ff
$primary = a8d9ff
$onPrimary = 102033
$primaryContainer = 36506a
$onPrimaryContainer = ffffff
$inversePrimary = 7da7cb
$secondary = d7e7f8
$onSecondary = 122033
$secondaryContainer = 253649
$onSecondaryContainer = dcecff
$tertiary = b9f3ff
$onTertiary = 0d2230
$tertiaryContainer = 274f60
$onTertiaryContainer = e6fbff
$error = ffb7c7
$onError = 3d0c17
$errorContainer = 6e1f2f
$onErrorContainer = ffd9e0
$primaryFixed = e8f5ff
$primaryFixedDim = a8d9ff
$onPrimaryFixed = 102033
$onPrimaryFixedVariant = 2d4661
$secondaryFixed = e9f2fb
$secondaryFixedDim = c6d7ea
$onSecondaryFixed = 122033
$onSecondaryFixedVariant = 304256
$tertiaryFixed = e7fbff
$tertiaryFixedDim = b9f3ff
$onTertiaryFixed = 0d2230
$onTertiaryFixedVariant = 2f5364
$term0 = 0c1219
$term1 = a8d9ff
$term2 = b9f3ff
$term3 = d7e7f8
$term4 = 7da7cb
$term5 = c6d7ea
$term6 = 95cfe8
$term7 = eaf4ff
$term8 = 607287
$term9 = c9efff
$term10 = dcfbff
$term11 = f6fbff
$term12 = a6bdd2
$term13 = d1e4f4
$term14 = b6e5f2
$term15 = ffffff
$rosewater = f6fbff
$flamingo = e9f2fb
$pink = dcecff
$mauve = c6d7ea
$red = ffb7c7
$maroon = f1c3cf
$peach = d8e9f7
$yellow = f0f7ff
$green = d7ecff
$teal = cfeeff
$sky = c0e4ff
$sapphire = a8d9ff
$blue = 95cfe8
$lavender = d6e6f5
$text = eaf4ff
$subtext1 = c6d3e2
$subtext0 = 7d90a8
$overlay2 = 74899d
$overlay1 = 5f7387
$overlay0 = 4a5d70
$surface2 = 31465a
$surface1 = 243645
$surface0 = 182433
$base = 0f1721
$mantle = 0b1118
$crust = 081019
$success = d7ecff
$onSuccess = 102033
$successContainer = 234258
$onSuccessContainer = eaf4ff
$surfaced4 = 1a2838
